bash: manage.py: command not found
